# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: '5.x'
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.15
    - name: Test
      run: dotnet test --verbosity normal
    - name: Build linux-x64
      run: dotnet publish -c Release -r linux-x64 -p:PublishReadyToRun=true --sc -p:Version=${{ steps.gitversion.outputs.nuGetVersionV2 }}
    - name: Build linux-arm64
      run: dotnet publish -c Release -r linux-arm64 -p:PublishReadyToRun=true --sc -p:Version=${{ steps.gitversion.outputs.nuGetVersionV2 }}
    - name: Tar linux-x64 artifact
      run: tar -czvf sshman-${{ steps.gitversion.outputs.nuGetVersionV2 }}-linux-x64.tar.gz -C src/sshman/bin/Release/net6.0/linux-x64/publish/ .
    - name: Tar linux-arm64 artifact
      run: tar -czvf sshman-${{ steps.gitversion.outputs.nuGetVersionV2 }}-linux-arm64.tar.gz -C src/sshman/bin/Release/net6.0/linux-arm64/publish/ .
    - name: Upload linux-x64 artifact
      uses: actions/upload-artifact@v3
      with:
        name: sshman-${{ steps.gitversion.outputs.nuGetVersionV2 }}-linux-x64
        path: sshman-${{ steps.gitversion.outputs.nuGetVersionV2 }}-linux-x64.tar.gz
    - name: Upload linux-arm64 artifact
      uses: actions/upload-artifact@v3
      with:
        name: sshman-${{ steps.gitversion.outputs.nuGetVersionV2 }}-inux-arm64
        path: sshman-${{ steps.gitversion.outputs.nuGetVersionV2 }}-linux-arm64.tar.gz
